# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appoint',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Appoints', to='exam.User'),
            preserve_default=False,
        ),
    ]
