# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180223_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appoint',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
